const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
app.get('/', (_, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')));
app.post('/transcribe', (req, res) => res.json({ ok: true, received: req.body }));
const port = process.env.PORT || 8000;
app.listen(port, () => console.log(`Server on ${port}`));
